# Generated by Django 6.0 on 2026-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reader', 'Reader'), ('moderator', 'Moderator')], default='moderator', max_length=10),
        ),
    ]
