# Generated by Django 6.0 on 2026-01-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reader', 'Reader'), ('moderator', 'Moderator')], default='reader', max_length=10),
        ),
    ]
